name: harunet
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - matplotlib
  - pillow
  - scipy
  - scikit-image
  - tqdm
  - jupyter
  - pip
  - pip:
      - torch
      - torchvision
